# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d41272bba784d1f1d8c5974f3079e15f115051305bc77b5fdbb3cc1c24a7fd7f494506a158c08ea8c4542f1221ddab9a515235a6b048f9bd45c827ddf5b463e

test:
  secret_key_base: b593c7963e18da84bd560d17df57d299bde881f51c617378500c4b335e18143578f41a8c32724cdd736f122477d38f9d1f14147ccfb07ea87c02e73aa8d03f7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
